name: Deploy ADF

on:
  push:
    branches:
      - main   # change if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Replace secrets in parameters file
        run: |
          sed -i "s|\"value\": \"\"|\"value\": \"${{ secrets.LS_SQL25_PASSWORD }}\"|" ARMTemplateParametersForFactory.json
          sed -i "0,/\"value\": \"\"/s|\"value\": \"\"|\"value\": \"${{ secrets.LS_DATALAKE25_KEY }}\"|" ARMTemplateParametersForFactory.json
          sed -i "0,/\"value\": \"\"/s|\"value\": \"\"|\"value\": \"${{ secrets.LS_MYSQL_PASSWORD }}\"|" ARMTemplateParametersForFactory.json
          sed -i "0,/\"value\": \"\"/s|\"value\": \"\"|\"value\": \"${{ secrets.LS_SQLDB25_PASSWORD }}\"|" ARMTemplateParametersForFactory.json

      - name: Deploy ARM template
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: myResourceGroupName    # replace with your RG
          template: ./ARMTemplateForFactory.json
          parameters: ./ARMTemplateParametersForFactory.json
          deploymentMode: Incremental
